import type { ConferenceEntry } from '@/types'

// `date` / `dateEnd` are ISO (YYYY-MM-DD); the homepage formats and sorts them.
export const conferences: ConferenceEntry[] = [
  {
    event: 'HITCON 2026',
    detail: 'When AI Acts: Hacking the Age of Agentic Systems',
    country: 'tw',
    date: '2026-08-21',
    dateEnd: '2026-08-22',
    role: 'Attendee',
    href: 'https://hitcon.org/2026/zh-TW/',
  },
  {
    event: 'Hong Kong Python User Group',
    detail: 'HKPUG #99 - "Lie" to me, Python',
    country: 'hk',
    date: '2026-06-27',
    role: 'Attendee',
    href: 'https://www.meetup.com/pythonhk/events/315242135/',
  },
  {
    event: 'Hong Kong Linux User Group',
    detail: '香港 Linux 用家聚會 (2026 春)',
    country: 'hk',
    date: '2026-05-04',
    role: 'Attendee',
    href: 'https://www.meetup.com/hong-kong-linux-user-group/events/314395884/',
  },
  {
    event: 'Hong Kong Python User Group',
    detail: 'HKPUG #96 - Project Cool Down: Build a Smart AC AI with Python',
    country: 'hk',
    date: '2026-03-28',
    role: 'Attendee',
    href: 'https://www.meetup.com/pythonhk/events/313621864/',
  },
  {
    event: 'Hong Kong Python User Group',
    detail: 'HKPUG #94 - Controlling Reality: Tests & AI Memory',
    country: 'hk',
    date: '2026-02-13',
    role: 'Attendee',
    href: 'https://www.meetup.com/pythonhk/events/312888626/',
  },
  {
    event: 'Hong Kong Python User Group',
    detail: 'HKPUG #92 - The Hacker and Refactor',
    country: 'hk',
    date: '2025-11-29',
    role: 'Speaker',
    href: 'https://www.meetup.com/pythonhk/events/311740779/',
  },
  {
    event: 'PyCon HK 2025',
    detail: 'Sailing Together: "Raise the Sail, Let Python Prevail"',
    country: 'hk',
    date: '2025-10-11',
    dateEnd: '2025-10-12',
    role: 'Attendee',
    href: 'https://www.meetup.com/pythonhk/events/310985620/',
  },
  {
    event: 'Hong Kong Python User Group',
    detail: 'HKPUG #91 - Python Gems for Real World',
    country: 'hk',
    date: '2025-09-22',
    role: 'Attendee',
    href: 'https://www.meetup.com/pythonhk/events/310907812/',
  },
]
